class T5Tables:
    trade_classifications = {
        "Ab": "Data Repository",
        "Ag": "Agricultural",
        "An": "Ancient Site",
        "As": "Asteroid",
        "Ba": "Barren",
        "Co": "Cold",
        "Cp": "Subsector Capital",
        "Cs": "Sector Capital",
        "Cx": "Capital",
        "Cy": "Colony",
        "Da": "Danger (Amber Zone)",
        "De": "Desert",
        "Di": "Dieback (000-T)",
        "Fa": "Farming",
        "Fl": "Fluid",
        "Fo": "Forbidden (Red Zone)",
        "Fr": "Frozen",
        "Ga": "Garden World",
        "Ho": "Hot",
        "He": "Hellworld",
        "Hi": "High Population",
        "Ic": "Ice-Capped",
        "In": "Industrial",
        "Lk": "Locked",
        "Lo": "Low Population",
        "Mi": "Mining",
        "Mr": "Military Rule",
        "Na": "Non-agricultural",
        "Ni": "Non-industrial",
        "Oc": "Ocean World",
        "Pa": "Pre-Agricultural",
        "Pe": "Penal Colony",
        "Ph": "Pre-High",
        "Pi": "Pre-Industrial",
        "Po": "Poor",
        "Pr": "Pre-Rich",
        "Px": "Prison or Exile Camp",
        "Pz": "Puzzle (Amber Zone)",
        "Re": "Reserve",
        "Ri": "Rich",
        "Sa": "Satellite",
        "Tr": "Tropic",
        "Tu": "Tundra",
        "Tz": "Twilight Zone",
        "Va": "Vacuum",
        "Wa": "Water World"
    }

    buying_goods_trade_classifications_table = {
            "Ag": -1000,
            "As": -1000,
            "Ba": 1000,
            "De": 1000,
            "Fl": 1000,
            "Hi": -1000,
            "Ic": 0,
            "In": -1000,
            "Lo": 1000,
            "Na": 0,
            "Ni": 1000,
            "Po": -1000,
            "Ri": 1000,
            "Va": 1000
        }
    
    selling_goods_trade_classifications_table = {
        "Ag": "Ag As De Hi In Ri Va",
        "As": "As In Ri Va",
        "Ba": "In",
        "De": "De",
        "Fl": "Fl In",
        "Hi": "Hi",
        "In": "Ag As De Fl Hi In Ri Va",
        "Na": "As De Va",
        "Po": "Ag Hi In Ri",
        "Ri": "Ag De Hi In Ri",
        "Va": "As In Va"
    }