TRADE_CLASSIFICATIONS = {
    "Ab": "Data Repository",
    "Ag": "Agricultural",
    "An": "Ancient Site",
    "As": "Asteroid",
    "Ba": "Barren",
    "Co": "Cold",
    "Cp": "Subsector Capital",
    "Cs": "Sector Capital",
    "Cx": "Capital",
    "Cy": "Colony",
    "Da": "Danger (Amber Zone)",
    "De": "Desert",
    "Di": "Dieback (000-T)",
    "Fa": "Farming",
    "Fl": "Fluid",
    "Fo": "Forbidden (Red Zone)",
    "Fr": "Frozen",
    "Ga": "Garden World",
    "Ho": "Hot",
    "He": "Hellworld",
    "Hi": "High Population",
    "Ic": "Ice-Capped",
    "In": "Industrial",
    "Lk": "Locked",
    "Lo": "Low Population",
    "Mi": "Mining",
    "Mr": "Military Rule",
    "Na": "Non-agricultural",
    "Ni": "Non-industrial",
    "Oc": "Ocean World",
    "Pa": "Pre-Agricultural",
    "Pe": "Penal Colony",
    "Ph": "Pre-High",
    "Pi": "Pre-Industrial",
    "Po": "Poor",
    "Pr": "Pre-Rich",
    "Px": "Prison or Exile Camp",
    "Pz": "Puzzle (Amber Zone)",
    "Re": "Reserve",
    "Ri": "Rich",
    "Sa": "Satellite",
    "Tr": "Tropic",
    "Tu": "Tundra",
    "Tz": "Twilight Zone",
    "Va": "Vacuum",
    "Wa": "Water World",
}

BUYING_GOODS_TRADE_CLASSIFICATIONS_TABLE = {
    "Ag": -1000,
    "As": -1000,
    "Ba": 1000,
    "De": 1000,
    "Fl": 1000,
    "Hi": -1000,
    "Ic": 0,
    "In": -1000,
    "Lo": 1000,
    "Na": 0,
    "Ni": 1000,
    "Po": -1000,
    "Ri": 1000,
    "Va": 1000,
}

SELLING_GOODS_TRADE_CLASSIFICATIONS_TABLE = {
    "Ag": "Ag As De Hi In Ri Va",
    "As": "As In Ri Va",
    "Ba": "In",
    "De": "De",
    "Fl": "Fl In",
    "Hi": "Hi",
    "In": "Ag As De Fl Hi In Ri Va",
    "Na": "As De Va",
    "Po": "Ag Hi In Ri",
    "Ri": "Ag De Hi In Ri",
    "Va": "As In Va",
}

BROKERS = {
    "Broker-7+": ("A", 4, 0.2),
    "Broker-6": ("AB", 3, 0.15),
    "Broker-5": ("AB", 3, 0.15),
    "Broker-4": ("ABC", 2, 0.1),
    "Broker-3": ("ABC", 2, 0.1),
    "Broker-2": ("ABCD", 1, 0.05),
    "Broker-1": ("ABCD", 1, 0.05),
}

ACTUAL_VALUE = {
    -5: 0.4,
    -4: 0.5,
    -3: 0.7,
    -2: 0.8,
    -1: 0.9,
    0: 1.0,
    1: 1.1,
    2: 1.2,
    3: 1.3,
    4: 1.5,
    5: 1.7,
    6: 2.0,
    7: 3.0,
    8: 4.0,
}

SKILLS_BY_GROUP = {
    "DEFAULT_SKILLS": [
        "Actor",
        "Artist",
        "Athlete",
        "Author",
        "Comms",
        "Computer",
        "Driver",
        "Fighter",
        "Turrets",
        "Mechanic",
        "Steward",
        "Vacc Suit",
    ],
    "SKILLS": [
        "Admin",
        "Advocate",
        "Animals",
        "Athlete",
        "Broker",
        "Bureaucrat",
        "Comms",
        "Computer",
        "Counsellor",
        "Designer",
        "Diplomat",
        "Driver",
        "Explosives",
        "Fleet Tactics",
        "Flyer",
        "Forensics",
        "Gambler",
        "High-G",
        "Hostile Environ",
        "JOT",
        "Language",
        "Leader",
        "Liaison",
        "Mechanic",
        "Naval Architect",
        "Seafarer",
        "Stealth",
        "Strategy",
        "Streetwise",
        "Survey",
        "Survival",
        "Tactics",
        "Teacher",
        "Trader",
        "Vacc Suit",
        "Zero-G",
    ],
    "STARSHIP_SKILLS": [
        "Astrogator",
        "Engineer",
        "Gunner",
        "Medic",
        "Pilot",
        "Sensors",
        "Steward",
    ],
    "TRADES": [
        "Biologics",
        "Craftsman",
        "Electronics",
        "Fluidics",
        "Gravitics",
        "Magnetics",
        "Mechanic",
        "Photonics",
        "Polymers",
        "Programmer",
    ],
    "ARTS": ["Actor", "Artist", "Author", "Chef", "Dancer", "Musician"],
    "SOLDIER_SKILLS": [
        "Fighter",
        "Forward Observer",
        "Heavy Weapons",
        "Navigator",
        "Recon",
        "Sapper",
    ],
    "PERSONALS": ["Carouse", "Query", "Persuade", "Command"],
    "INTUITIONS": ["Curiosity", "Insight", "Luck"],
}
